services:
  postgres:
    image: postgres:latest
    user: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: screen_match
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  postgres: